name: Deploy to Apigee X

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/170171199217/locations/global/workloadIdentityPools/apigee-workflowgithub/providers/apigee-workflowoidc"
          service_account: "madhavitest@temporal-trees-475907-i1.iam.gserviceaccount.com"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.9.9'

      - name: Deploy to Apigee
        run: |
          mvn install -P apigee \
            -Dorg=${{ secrets.APIGEE_ORGANIZATION }} \
            -Denv=${{ secrets.APIGEE_ENVIRONMENT }} \
            -Dapigee.token=$(gcloud auth print-access-token) \
            apigee-enterprise:deploy
